whttp:
  host: 0.0.0.0
  port: "8081"
  
https:
  host: 0.0.0.0
  port: "8082"

mongodb:
  link: ${secure::mongodb.link}
  
keystore:
  type: "JKS"
  path: "keystore/keystore-dev.jks"
  alias: "${secure::keystore.alias}"
  password: "${secure::keystore.password}"
  