keystore:
  password: "![Xy1FWSDYdKgAB+1gNeY48w==]"
  alias: "![7yacZh9F1XfJ1mlUxI8VhQ==]"
    
mongodb:
  link: "![xYURFbbnHJ9cz0/L/Y/fctyOjQRYglCZy4dNLTy8NekpZfVjlNvZK1z4guVhd/DGMlq6hT6JB2DR/rOMBTUR04Tn9kNppFrNxrdMNl1PBkjRDmw3XCzraTvjRpF0XpED]"

  
